version: "3.8"

services:
  analisis-numerico:
    container_name: analisis-numerico
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-net

  fastapi-backend:
    container_name: fastapi-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
