version: "3.8"

services:
  analisis-numerico:
    container_name: analisis-numerico
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-net

  fastapi-backend:
    container_name: fastapi-backend
    build:
      context: ../backend # ← o ajustá si la carpeta es distinta
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
